### ISSUE TITLE
Use c compiler for c files.

### ISSUE THREAD

**Issue by heydwdev** [dwalker0044/Aim#34]
Currently the C++ compiler is used for all file types. This isn't valid for C files as you get the warning:
```
clang-10: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
```

**Comment by SarveshLele** [comment]
If you are using GNU compiler in Windows, you can go to Compiler Options. There you will see a dropdown with value C++. Select the dropdown and select a Null(Empty) value. This should solve it.

**Comment by heydwdev** [comment]
Thank you for you comment @SarveshLele  but the issue really lies at the fact that Aim should switch to using a C compiler when it detects c files. At the moment it uses the c++ for everything which is incorrect.
